In [69]:
import numpy as np
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd

In [32]:
# # Цель: Выполнить сингулярное разложение в python и записать получившуюся матрицу преобразования для следующих матриц: 
# # 1)A=[[3, 7], [5, 2]] 
# # 2)B=[[0, 1, 3], [2, 3, 1], [0, 1, 0]] 
# 3) C = [
#     [5, 7, 6, 4, 2,],
#     [1, 3, 4, 1, 3,],
#     [3, 4, 5, 4, 1,],
# ]

In [66]:
a = np.array([[3, 7], [5, 2]])
u,s,vt = svd(a)
Sigma = np.diag(s)
res = u.dot(Sigma.dot(vt))
res.astype(int)

array([[3, 7],
       [5, 2]])

In [67]:
b = np.array([
    [0, 1, 3], 
    [2, 3, 1],
    [0, 1, 0]
])
u,s,vt = svd(b)
Sigma = diag(s)
res = u.dot(Sigma.dot(vt))
res.astype(int)

array([[0, 1, 3],
       [2, 3, 1],
       [0, 1, 0]])

In [63]:
c = array([
    [5, 7, 6, 4, 2,],
    [1, 3, 4, 1, 3,],
    [3, 4, 5, 4, 1,],
])
u, s, vt = svd(c)
Sigma = zeros((c.shape[0], c.shape[1]))
Sigma[:c.shape[1], :c.shape[0]] = diag(s)
check = U.dot(Sigma.dot(VT))
check.astype(int)

array([[5, 7, 6, 4, 2],
       [1, 3, 4, 1, 3],
       [3, 4, 5, 4, 1]])